import Head from 'next/head'
import Allinone from './components/Allinone'
import Brands from './components/Brands'
import Domain from './components/Domain'
import Features from './components/Features'
import Footer from './components/Footer'
import Guranty from './components/Guranty'
import Herosection from './components/Herosection'
import Navbar from './components/Navbar'
import Pricingsection from './components/Pricingsection'
import Qualities from './components/Qualities'
import Testimonials from './components/Testimonials'
import Userpannel from './components/Userpannel'
import Vedio1 from './components/Vedio1'
import Vedio2 from './components/Vedio2'
import Vedio3 from './components/Vedio3'
import Vedio4 from './components/Vedio4'
import Vedio5 from './components/Vedio5'
import React, { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {
  useEffect(() => {
    AOS.init({ duration: 1000 });
  }, []);
  return (
    <div>
      <Head>
        <title>Hostinger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Redesign of Hostinger.com" />
        <meta name="description" content="Made by Tailwind css" />
        <meta name="description" content="Also Made from animate-on-scroll library." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Herosection />
      <Brands />
      <Allinone />
      <Features />
      <Domain />
      <Pricingsection />
      <Qualities />
      <Vedio1 />
      <Vedio2 />
      <Vedio3 />
      <Vedio4 />
      <Vedio5 />
      <Userpannel />
      <Testimonials />
      <Guranty />
      <Footer />

    </div>
  )
}
